-- ─────────────────────────────────────────────────────────────────────────────
-- 04 — Retired 2026-08-23.
--
-- This file used to create publication `icc26_cdc` over lims.sample_result and
-- mes.batch_event. Neither table has a CDC consumer and neither ever did:
-- pattern 5 tails database `apconnect` instead (see 05-apconnect.sql), which is
-- the turbidity meter's data-management application and the only source in this
-- stack that a change-data-capture story is honest about.
--
-- The file stays for two reasons: initdb numbering has no hole, and a grep for
-- `icc26_cdc` still finds this explanation rather than nothing.
--
-- Do not put the publication back. A publication with no subscriber is exactly
-- how somebody later "fixes" CDC back onto the LIMS tables, and the 2026-08-19
-- LIMS triple (webhook + CDC + poll of one table) is the reversal this repo has
-- already made once.
--
-- `wal_level=logical` is unaffected and still required. It is a server start
-- parameter set in the compose `command:` override, not here, because changing
-- it later means dropping the data volume.
--
-- Verify after first boot:  SHOW wal_level;  -->  logical
--                           SELECT pubname FROM pg_publication;  --> apconnect_cdc only
-- ─────────────────────────────────────────────────────────────────────────────

-- Intentionally no statements.
